# Generated by Django 4.2.5 on 2023-09-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('property', models.TextField(blank=True, null=True)),
                ('use', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='Herbs/')),
                ('favorite', models.BooleanField()),
            ],
        ),
    ]
