# Generated by Django 4.2.5 on 2023-10-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_herb_favorite_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herb',
            old_name='property',
            new_name='med_property',
        ),
        migrations.RenameField(
            model_name='herb',
            old_name='use',
            new_name='med_use',
        ),
        migrations.AddField(
            model_name='herb',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
