# Generated by Django 4.2.5 on 2023-10-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_property_herb_med_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='potential_SE',
            field=models.TextField(blank=True, null=True),
        ),
    ]
