# Generated by Django 4.2.5 on 2023-10-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_store_herb_lat_herb_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='scientific_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
