# Generated by Django 4.2.5 on 2023-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_herb_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='habitat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
