# Generated by Django 4.2.5 on 2023-11-09 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_herb_habitat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapHerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='HerbMap/')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
