# Generated by Django 4.2.5 on 2023-11-10 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mapcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
