# Generated by Django 4.2.5 on 2023-11-13 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='herb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.herb'),
        ),
        migrations.AlterField(
            model_name='mapcomment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapcomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mapherb',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapherb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='herb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.herb'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony', to=settings.AUTH_USER_MODEL),
        ),
    ]
