# Generated by Django 4.2.5 on 2023-11-14 11:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_datasets_images_datasetimages_datasets_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetimages',
            name='images',
            field=models.ImageField(upload_to=core.models.upload_to_dataset, verbose_name='Image'),
        ),
    ]
