# Generated by Django 4.2.5 on 2023-11-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_dataset_datasetimages_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb', models.FileField(upload_to='MachineModel/')),
                ('label', models.FileField(upload_to='MachineModel/')),
            ],
        ),
        migrations.AlterField(
            model_name='datasetimages',
            name='class_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasetimageclass', to='core.datasets'),
        ),
    ]
