# Generated by Django 4.2.5 on 2023-11-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_herbalistprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image',
            field=models.ImageField(upload_to='Herbs/'),
        ),
    ]
