# Generated by Django 4.2.5 on 2023-11-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_herb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image',
            field=models.FileField(upload_to='Herbs/'),
        ),
    ]
